<------------------------------------------------------------------------------------------------------------------------>
IDENTIFICATION DIVISION.
PROGRAM-ID DATACLEAN.
DATE: 11/13/2024 TO 11/16/2024
AUTHOR: CATARINA CORREIA DA COSTA 
STUDENTID: A048002
<------------------------------------------------------------------------------------------------------------------------>

Começo por importar as bibliotecas necessárias como as seguintes: 
pandas e numpy para análise de dados e constituição de dataframe para limpeza de dados.
re para cáclulos que possa precisar para obtenção de mais dados que possam parecer relevantes á investigação.

In [3]:
import pandas as pd
import numpy as np
import re as re

Seguidamente, nos ficheiros que nos foram fornecidos, encontrava-se um ficheiro .txt com details. 
Fiz um pequeno pedaço de código que me pernmitisse ler esse ficheiro e apresentar-me o seu conteúdo (imprimir linhas do mesmo). Achei que não seria por acaso que o mesmo estaria aqui, tanbém fora alvo de conteúdo de dados relevantes.

In [5]:
 # Mostrar txt e mostrar texto nele contido.
try:
    with open("details.txt", "r", encoding="utf-8") as file:  # ficheiro txt a ler
        lines = file.readlines()
    
    # Mostrar as primeiras linhas do ficheiro
        print(lines)
        
except FileNotFoundError:
    print("Error: The file 'details.txt' was not found. Please check the file path.")
except UnicodeDecodeError:
    print("Error: Unable to decode the file. Try specifying a different encoding (e.g., 'utf-8' or 'ISO-8859-1').")
except PermissionError:
    print("Error: Permission denied. Ensure the file is not locked or being used by another program.")

['Description:\n', '\n', 'The sinking of the Titanic is one of the most infamous shipwrecks in history.\n', '\n', 'On April 15, 1912, during her maiden voyage, the widely considered “unsinkable” RMS Titanic sank after colliding with an iceberg. Unfortunately, there weren’t enough lifeboats for everyone on board, resulting in the death of 1502 out of 2224 passengers and crew.\n', '\n', 'While there was some element of luck involved in surviving, it seems some groups of people were more likely to survive than others.\n', '\n', 'In this challenge, we ask you to build a predictive model that answers the question: “what sorts of people were more likely to survive?” using passenger data (ie name, age, gender, socio-economic class, etc).\n', 'Acknowledgements:\n', '\n', 'This dataset has been referred from Kaggle: https://www.kaggle.com/c/titanic/data.\n', '\n', 'For more details, check also: https://www.kaggle.com/datasets/yasserh/titanic-dataset\n']

Após análise do conteúdo dass linhas encvontro algumas informações qu mais tarde me irão servir para o dataset, tais como:
- número de pessoas que morreram;
- Total de pessoas a bordo.
Feita a busca e o match com a informação a mesma é armazenada em variavel e impressa.

In [7]:
#Informacao retirada do txt 
#total de pessoas a bordo e de mortos
#import re

# Dados obtidos txt anteriormente

description = """
The sinking of the Titanic is one of the most infamous shipwrecks in history.

On April 15, 1912, during her maiden voyage, the widely considered “unsinkable” RMS Titanic sank after colliding with an iceberg. Unfortunately, there weren’t enough lifeboats for everyone on board, resulting in the death of 1502 out of 2224 passengers and crew.

While there was some element of luck involved in surviving, it seems some groups of people were more likely to survive than others.

In this challenge, we ask you to build a predictive model that answers the question: “what sorts of people were more likely to survive?” using passenger data (ie name, age, gender, socio-economic class, etc).
"""

# Procurar números relevantes 
died_pattern = r"death of (\d+) out of (\d+) passengers"
match = re.search(died_pattern, description)

if match:
    # Procurar match com a informação relevante 
    died = int(match.group(1))  # Number of people who died
    total = int(match.group(2))  # Total number of people on board

    print(f"Total number of people on board: {total}")
    print(f"Number of people who died: {died}")
else:
    print("Data not found in the text")

Total number of people on board: 2224
Number of people who died: 1502

Para além das informações acima retiradas do texto, podemos encontrar mais informaçã relevante como:
- data do acontecimento
- problema e a descrição do mesmo
- Questão da investigaçãqo
Este pedaço de códgico busca esses elementos e se tiver um match ele guarda em variavel e imprime.

In [9]:
#import pandas as pd

# Dados do ficheiro txt
description = """
The sinking of the Titanic is one of the most infamous shipwrecks in history.

On April 15, 1912, during her maiden voyage, the widely considered “unsinkable” RMS Titanic sank after colliding with an iceberg. Unfortunately, there weren’t enough lifeboats for everyone on board, resulting in the death of 1502 out of 2224 passengers and crew.

While there was some element of luck involved in surviving, it seems some groups of people were more likely to survive than others.

In this challenge, we ask you to build a predictive model that answers the question: “what sorts of people were more likely to survive?” using passenger data (ie name, age, gender, socio-economic class, etc).
"""

# Extração da data,do problema e da questão de investigação
date = "April 15, 1912"
Problem= "RMS Titanic sank after colliding with an iceberg. Unfortunately, there weren’t enough lifeboats for everyone on board,"
question_of_study = "What sorts of people were more likely to survive the sinking of the RMS Titanic?"

# Definir os dados em forma de dicionário
data = {
    'Date': [date],
    'Problem':[Problem],
    'Question_of_Study': [question_of_study]
}

# Criar  DataFrame
df = pd.DataFrame(data)

# Apresentar  DataFrame
print(df)

             Date                                            Problem  \
0  April 15, 1912  RMS Titanic sank after colliding with an icebe...

                                   Question_of_Study
0  What sorts of people were more likely to survi...

Com o ficheiro dataset de origem começo por ler o mesmo e imprimir as primeiras linhas para ver como está organizado.

WORKING-STORAGE SECTION.

In [12]:
# ler csv e mostrar algumsas linhas 

#import pandas as pd 

df = pd.read_csv("Titanic-Dataset - copia.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Peço para me listar todas as variáveis do dataset

DATA DIVISION.

In [15]:
#variaveis do dataset
#import pandas as pd

# Ler dataset 
df = pd.read_csv('Titanic-Dataset - copia.csv')

# Apresentar o nome das colunas (variaveis)
print("Variables in the dataset:", df.columns)

Variables in the dataset: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Peço também os tipos de dados que as colunas têm para saber se estão corretos os valores introduzidos.

In [17]:
print("Column data types:\n", df.dtypes) # msostrar tipos de dados das coluinas

Column data types:
 PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Peço informação completa do dataset para ver por onde começo a limpar (valores nulos,memória,número de colunas e linhas total).


       PROCEDURE DIVISION.

In [20]:
print(df.info())  #mostrar toda a informação da tabela

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

Começo a limpeza de dados pela contagem de valores nulos e onde eles se encontram na tabela, para decidir o que fazer com cada uma das clolunas.

In [22]:
#Nan and null what i do?
#import pandas as pd

# Ler dataset
# df = pd.read_csv('Titanic-Dataset - copia.csv')

# Contar os valores omissos em cada coluna
nan_counts = df.isna().sum()

# Mostrar quantos valores estão omissos e as colunas a que eles correspondem
print("NaN values per column:")
print(nan_counts[nan_counts > 0])

NaN values per column:
Age         177
Cabin       687
Embarked      2
dtype: int64

Aqui tentei que a ccoluna name fosse dividida em lastname firstname e ao mesmo tempo que na mesma coluna se apagasse espaço em branco a mais, com intuito  de formatar.
Passar survied 1 e not survied 0 para categoria para facilitar a leitura
Adicionei uma coluna de tamanho da familia que ajuda a entender quantas famílias completas iam na viagem e quantos da família sobreviveram (cálculos ainda a realizar).

In [24]:
#import pandas as pd
#import numpy as np

# ler dataet
#df = pd.read_csv("Titanic-Dataset - copia.csv")

#Apresentar o dataframe inicial
print("Original DataFrame:\n", df.head())

# split name em lastname e firstname

df[['LastName', 'FirstName']] = df['Name'].str.split(',', expand=True)
#limpar espaços em branco extra

df['FirstName'] = df['FirstName'].str.strip()

#conerter survived coluna em categorias para ser mais simples em vez de 0 e 1

df['Survived'] = df['Survived'].map({1: 'Survived', 0: 'Did not survive'})

#Adicionar a coluna tamanho da família para saber quantas pessoas eram da mesma família

if 'SibSp' in df.columns and 'Parch' in df.columns:
    df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
else:
    print("Error: 'SibSp' or 'Parch' column is missing, cannot compute 'FamilySize'.")
    
# Mostrar as alterações feitas no dataframe
print("\nTransformed DataFrame:\n", df.head())

Original DataFrame:
    PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

Transformed DataFrame:
    PassengerId         Survived  Pclass  \
0            1  Did not survive       3
1            2         Survived       1
2            3         Survived       3
3            4         Survived       1
4            5  Did not survive       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked   LastName  \
0      0         A/5 21171   7.2500   NaN        S     Braund
1      0          PC 17599  71.2833   C85        C    Cumings
2      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen
3      0            113803  53.1000  C123        S   Futrelle
4      0            373450   8.0500   NaN        S      Allen

                                    FirstName  FamilySize
0                             Mr. Owen Harris           2
1  Mrs. John Bradley (Florence Briggs Thayer)           2
2                                 Miss. Laina           1
3          Mrs. Jacques Heath (Lily May Peel)           2
4                           Mr. William Henry           1

Neste passo, fiz uma contagem de nulls, ou seja, valores nan e none em todo o dataset e que me identificasse em que colunas estva presente esse valor e quantos.

In [26]:
# Contagem dos valores nulos (None, NAN)
# leitura do CSV 
#df = pd.read_csv('Titanic-Dataset - copia.csv')

# Contagem  NaN/None valores em cada coluna

nan_count_per_column = df.isna().sum()

# Contagem dos  NaN/None valores em todo o  DataFrame

nan_count_total = df.isna().sum().sum()

# Mostrar as contagens 

print("NaN/None values per column:")
print(nan_count_per_column)

print("\nTotal NaN/None values in the DataFrame:", nan_count_total)

NaN/None values per column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
LastName         0
FirstName        0
FamilySize       0
dtype: int64

Total NaN/None values in the DataFrame: 866

Segundo a tabela acima temos valores nulos nas seguintes tabela:
-Age 
-Embarked
- Cabin
Momento de decisões...... hummmm que faço?
Ora bem, o mais pequeno embarked posso ir pelo valor mais frequente (mode).
Age temos dois problemas tem o datatype errado float podemos ver mais acima e tem valores nulos.
Como quero resolver ambos os problemas (passar a integer e usar a mediana para completar os nulls)
cabin? pois esse vai ser mais difícil, mais adiante um de cada vez ou talvez dois

In [28]:
#import pandas as pd

# Ler ficheiro CSV
#df = pd.read_csv('Titanic-Dataset - copia.csv')

#´Preencher valores omissos em Age com a média e converter em número inteiro

df['Age'] = df['Age'].fillna(df['Age'].median()).round().astype(int)

#Preencher valores omissos em Embarked com mode (valor mais frequente)

df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

#Verificar se aiinda existem valres omissos

print("\nMissing values after handling:")
print(df.isna().sum())


#Mostrar novo dataframe com as alterações

print("\nUpdated DataFrame:")
print(df.head())

Missing values after handling:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
LastName         0
FirstName        0
FamilySize       0
dtype: int64

Updated DataFrame:
   PassengerId         Survived  Pclass  \
0            1  Did not survive       3
1            2         Survived       1
2            3         Survived       3
3            4         Survived       1
4            5  Did not survive       3

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1
2                             Heikkinen, Miss. Laina  female   26      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1
4                           Allen, Mr. William Henry    male   35      0

   Parch            Ticket     Fare Cabin Embarked   LastName  \
0      0         A/5 21171   7.2500   NaN        S     Braund
1      0          PC 17599  71.2833   C85        C    Cumings
2      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen
3      0            113803  53.1000  C123        S   Futrelle
4      0            373450   8.0500   NaN        S      Allen

                                    FirstName  FamilySize
0                             Mr. Owen Harris           2
1  Mrs. John Bradley (Florence Briggs Thayer)           2
2                                 Miss. Laina           1
3          Mrs. Jacques Heath (Lily May Peel)           2
4                           Mr. William Henry           1

Preciso que me mostre todos os null de cabin para serem resolvidos

In [30]:
#NULL na coluna cabin

df[df['Cabin'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,LastName,FirstName,FamilySize
0,1,Did not survive,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris,2
2,3,Survived,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina,1
4,5,Did not survive,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry,1
5,6,Did not survive,3,"Moran, Mr. James",male,28,0,0,330877,8.4583,NaN,Q,Moran,Mr. James,1
7,8,Did not survive,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750,NaN,S,Palsson,Master. Gosta Leonard,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,Did not survive,3,"Sutehall, Mr. Henry Jr",male,25,0,0,SOTON/OQ 392076,7.0500,NaN,S,Sutehall,Mr. Henry Jr,1
885,886,Did not survive,3,"Rice, Mrs. William (Margaret Norton)",female,39,0,5,382652,29.1250,NaN,Q,Rice,Mrs. William (Margaret Norton),6
886,887,Did not survive,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,NaN,S,Montvila,Rev. Juozas,1
888,889,Did not survive,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28,1,2,W./C. 6607,23.4500,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie""",4
890,891,Did not survive,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,NaN,Q,Dooley,Mr. Patrick,1

Para resolver o problema da cabin ter valores nulos decidi recorrer ao ticket. Este é composto normalmente por uma letra e um conjunto de números, a letra corresponde ao deck e á cabine. Tenho uma lista anterior dos decks válidos e vou transformar o bilhete (ticket) em string e verificar se a letra extraida  corresponde com um deck válido. Caso simm, preenche deck+cabin, caso não fica os dados do bilhete.
Apago a coluna ticket-deck que usei na correspondência e imprimo o dataframe atualizado.

In [32]:

#import pandas as pd

# Leitura do csv
#df = pd.read_csv('Titanic-Dataset - copia.csv')

# Transformação da coluna Ticket em string 
df['Ticket'] = df['Ticket'].astype(str)

# Extrair a primeira letra que corresponda com o deck e colocar em maiuscula 
df['Ticket_Deck'] = df['Ticket'].str[0].str.upper()

# Verificar se corresponde a um deck
valid_decks = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'T']
df['Ticket_Deck'] = df['Ticket_Deck'].apply(lambda x: x if x in valid_decks else None)

# Preencher com o valor do ticket em caso de ser inválido ou não existir
df['Cabin'] = df['Cabin'].fillna(df['Ticket_Deck'])

df.drop(columns=['Ticket_Deck'], inplace=True)

# Mostrar dataframe atualizado
print(df)

#Vou verificar se ainda existem valores nulos nessa coluna
print(df['Cabin'].isnull().sum())

     PassengerId         Survived  Pclass  \
0              1  Did not survive       3
1              2         Survived       1
2              3         Survived       3
3              4         Survived       1
4              5  Did not survive       3
..           ...              ...     ...
886          887  Did not survive       2
887          888         Survived       1
888          889  Did not survive       3
889          890         Survived       1
890          891  Did not survive       3

                                                  Name     Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    male   22      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1
2                               Heikkinen, Miss. Laina  female   26      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1
4                             Allen, Mr. William Henry    male   35      0
..                                                 ...     ...  ...    ...
886                              Montvila, Rev. Juozas    male   27      0
887                       Graham, Miss. Margaret Edith  female   19      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   28      1
889                              Behr, Mr. Karl Howell    male   26      0
890                                Dooley, Mr. Patrick    male   32      0

     Parch            Ticket     Fare Cabin Embarked   LastName  \
0        0         A/5 21171   7.2500     A        S     Braund
1        0          PC 17599  71.2833   C85        C    Cumings
2        0  STON/O2. 3101282   7.9250  None        S  Heikkinen
3        0            113803  53.1000  C123        S   Futrelle
4        0            373450   8.0500  None        S      Allen
..     ...               ...      ...   ...      ...        ...
886      0            211536  13.0000  None        S   Montvila
887      0            112053  30.0000   B42        S     Graham
888      2        W./C. 6607  23.4500  None        S   Johnston
889      0            111369  30.0000  C148        C       Behr
890      0            370376   7.7500  None        Q     Dooley

                                      FirstName  FamilySize
0                               Mr. Owen Harris           2
1    Mrs. John Bradley (Florence Briggs Thayer)           2
2                                   Miss. Laina           1
3            Mrs. Jacques Heath (Lily May Peel)           2
4                             Mr. William Henry           1
..                                          ...         ...
886                                 Rev. Juozas           1
887                        Miss. Margaret Edith           1
888              Miss. Catherine Helen "Carrie"           4
889                             Mr. Karl Howell           1
890                                 Mr. Patrick           1

[891 rows x 15 columns]
607

Devido á existência de muitos valores nulos, mesmo após a ajuda dada pelo ticket, optei por passar a unknown esses valores para não perder as linhas na eliminação de dados. Assim, passam a não contabilizados.

In [34]:

#Substitui NAN and NONE for Unknown

#import pandas as pd

# Ler o csv
#df = pd.read_csv('Titanic-Dataset - copia.csv')

# Substituir NaN  na coluna  'Cabin' por 'Unknown'
df['Cabin'] = df['Cabin'].fillna('Unknown')

# Passar todos os elementos as maíusculas
df['Cabin'] = df['Cabin'].apply(lambda x: x.upper())

print("\nDataFrame after filling NaN values and transforming 'Cabin':")
print(df.head())

DataFrame after filling NaN values and transforming 'Cabin':
   PassengerId         Survived  Pclass  \
0            1  Did not survive       3
1            2         Survived       1
2            3         Survived       3
3            4         Survived       1
4            5  Did not survive       3

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1
2                             Heikkinen, Miss. Laina  female   26      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1
4                           Allen, Mr. William Henry    male   35      0

   Parch            Ticket     Fare    Cabin Embarked   LastName  \
0      0         A/5 21171   7.2500        A        S     Braund
1      0          PC 17599  71.2833      C85        C    Cumings
2      0  STON/O2. 3101282   7.9250  UNKNOWN        S  Heikkinen
3      0            113803  53.1000     C123        S   Futrelle
4      0            373450   8.0500  UNKNOWN        S      Allen

                                    FirstName  FamilySize
0                             Mr. Owen Harris           2
1  Mrs. John Bradley (Florence Briggs Thayer)           2
2                                 Miss. Laina           1
3          Mrs. Jacques Heath (Lily May Peel)           2
4                           Mr. William Henry           1

Como podemos verificar, foi utilizado o número de ticket, este é composto por números que indicam o acento e letras correspondem ao deck e este por sua vez corresponde a uma cabine, exemplo   A/5 21171  é a cabine A e o deck A.
Assim,pude preencher alguns dos valores nulos, no entanto, nem todos os números de bilhete possuiam cabine, por isso passaram a none e para não serem contabilizados terei que os passar a unknown e assim completar a deck colum e alterar o dataframe de forma a eliminar nulos sem seleimnar linhas completas.
Porque se as eliminasse perderia outros dados relevantes e este poderá não o ser, mas não perco os restantes eliminando linhas ou a coluna.

In [36]:
#Ignorar UnKnown

# Mostrar primeiras linhas para verificar os dados iniciais

print("Initial DataFrame:")
print(df.head())

#Extrair a primeira letra dos elementos de cabin ignorando (NAN e None)

df['Cabin'] = df['Cabin'].apply(lambda x: str(x)[0] if pd.notna(x) else x)
#A primeira letra de Cabin é considerado o deck 

#A primeira letra de Cabin é considerado o deck 

df['Deck'] = df['Cabin'].str[0]  

#Mostrar as alterações no dataframe

print("\nDataFrame after processing 'Cabin' column:")
print(df.head())

Initial DataFrame:
   PassengerId         Survived  Pclass  \
0            1  Did not survive       3
1            2         Survived       1
2            3         Survived       3
3            4         Survived       1
4            5  Did not survive       3

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1
2                             Heikkinen, Miss. Laina  female   26      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1
4                           Allen, Mr. William Henry    male   35      0

   Parch            Ticket     Fare    Cabin Embarked   LastName  \
0      0         A/5 21171   7.2500        A        S     Braund
1      0          PC 17599  71.2833      C85        C    Cumings
2      0  STON/O2. 3101282   7.9250  UNKNOWN        S  Heikkinen
3      0            113803  53.1000     C123        S   Futrelle
4      0            373450   8.0500  UNKNOWN        S      Allen

                                    FirstName  FamilySize
0                             Mr. Owen Harris           2
1  Mrs. John Bradley (Florence Briggs Thayer)           2
2                                 Miss. Laina           1
3          Mrs. Jacques Heath (Lily May Peel)           2
4                           Mr. William Henry           1

DataFrame after processing 'Cabin' column:
   PassengerId         Survived  Pclass  \
0            1  Did not survive       3
1            2         Survived       1
2            3         Survived       3
3            4         Survived       1
4            5  Did not survive       3

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1
2                             Heikkinen, Miss. Laina  female   26      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1
4                           Allen, Mr. William Henry    male   35      0

   Parch            Ticket     Fare Cabin Embarked   LastName  \
0      0         A/5 21171   7.2500     A        S     Braund
1      0          PC 17599  71.2833     C        C    Cumings
2      0  STON/O2. 3101282   7.9250     U        S  Heikkinen
3      0            113803  53.1000     C        S   Futrelle
4      0            373450   8.0500     U        S      Allen

                                    FirstName  FamilySize Deck
0                             Mr. Owen Harris           2    A
1  Mrs. John Bradley (Florence Briggs Thayer)           2    C
2                                 Miss. Laina           1    U
3          Mrs. Jacques Heath (Lily May Peel)           2    C
4                           Mr. William Henry           1    U

Também uma coluna que lista os títulos de cada nome. 
São dados que podem mais tarde explicar a sorte e também o estatuto socio económico do documento ddetails.

In [38]:
#Títulos de famílias -filtrar

def filter_by_titles(titles):
    """
    Filter the global DataFrame to include only rows where the 'Title' column matches the specified titles

    Args:
        titles (list): List of titles to filter (e.g., ['Miss', 'Mr', 'Mrs']).

    Returns:
        pd.DataFrame: A DataFrame containing only rows with the specified titles.
    """
    global df
    
    #Extrair títulos de nome
    df['Title'] = df['Name'].str.extract(r'\b(' + '|'.join(titles) + r')\b', expand=True)

    # Restringir-me ás colunas onde se localizam os títtulos = nome
    return df[df['Title'].isin(titles)]

# Lista de títulos a procurar
desired_titles = ['Miss', 'Mr', 'Mrs', 'Dr', 'Master']

#  DataFrame - filtrar e procurar 
filtered_df = filter_by_titles(desired_titles)

# Mostrar os valores retirados do dataframe coluna nome titulo
print(filtered_df[['Name', 'Title']])

                                                  Name Title
0                              Braund, Mr. Owen Harris    Mr
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   Mrs
2                               Heikkinen, Miss. Laina  Miss
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   Mrs
4                             Allen, Mr. William Henry    Mr
..                                                 ...   ...
885               Rice, Mrs. William (Margaret Norton)   Mrs
887                       Graham, Miss. Margaret Edith  Miss
888           Johnston, Miss. Catherine Helen "Carrie"  Miss
889                              Behr, Mr. Karl Howell    Mr
890                                Dooley, Mr. Patrick    Mr

[874 rows x 2 columns]

Quis ver todod o dataframe completo

In [40]:
#import pandas as pd
# ver database completo
pd.options.display.max_rows = None
pd.options.display.max_columns=None

#df = pd.read_csv('Titanic-Dataset - copia.csv')

print(df)

     PassengerId         Survived  Pclass  \
0              1  Did not survive       3
1              2         Survived       1
2              3         Survived       3
3              4         Survived       1
4              5  Did not survive       3
5              6  Did not survive       3
6              7  Did not survive       1
7              8  Did not survive       3
8              9         Survived       3
9             10         Survived       2
10            11         Survived       3
11            12         Survived       1
12            13  Did not survive       3
13            14  Did not survive       3
14            15  Did not survive       3
15            16         Survived       2
16            17  Did not survive       3
17            18         Survived       2
18            19  Did not survive       3
19            20         Survived       3
20            21  Did not survive       2
21            22         Survived       2
22            23         Survived       3
23            24         Survived       1
24            25  Did not survive       3
25            26         Survived       3
26            27  Did not survive       3
27            28  Did not survive       1
28            29         Survived       3
29            30  Did not survive       3
30            31  Did not survive       1
31            32         Survived       1
32            33         Survived       3
33            34  Did not survive       2
34            35  Did not survive       1
35            36  Did not survive       1
36            37         Survived       3
37            38  Did not survive       3
38            39  Did not survive       3
39            40         Survived       3
40            41  Did not survive       3
41            42  Did not survive       2
42            43  Did not survive       3
43            44         Survived       2
44            45         Survived       3
45            46  Did not survive       3
46            47  Did not survive       3
47            48         Survived       3
48            49  Did not survive       3
49            50  Did not survive       3
50            51  Did not survive       3
51            52  Did not survive       3
52            53         Survived       1
53            54         Survived       2
54            55  Did not survive       1
55            56         Survived       1
56            57         Survived       2
57            58  Did not survive       3
58            59         Survived       2
59            60  Did not survive       3
60            61  Did not survive       3
61            62         Survived       1
62            63  Did not survive       1
63            64  Did not survive       3
64            65  Did not survive       1
65            66         Survived       3
66            67         Survived       2
67            68  Did not survive       3
68            69         Survived       3
69            70  Did not survive       3
70            71  Did not survive       2
71            72  Did not survive       3
72            73  Did not survive       2
73            74  Did not survive       3
74            75         Survived       3
75            76  Did not survive       3
76            77  Did not survive       3
77            78  Did not survive       3
78            79         Survived       2
79            80         Survived       3
80            81  Did not survive       3
81            82         Survived       3
82            83         Survived       3
83            84  Did not survive       1
84            85         Survived       2
85            86         Survived       3
86            87  Did not survive       3
87            88  Did not survive       3
88            89         Survived       1
89            90  Did not survive       3
90            91  Did not survive       3
91            92  Did not survive       3
92            93  Did not survive       1
93            94  Did not survive       3
94            95  Did not survive       3
95            96  Did not survive       3
96            97  Did not survive       1
97            98         Survived       1
98            99         Survived       2
99           100  Did not survive       2
100          101  Did not survive       3
101          102  Did not survive       3
102          103  Did not survive       1
103          104  Did not survive       3
104          105  Did not survive       3
105          106  Did not survive       3
106          107         Survived       3
107          108         Survived       3
108          109  Did not survive       3
109          110         Survived       3
110          111  Did not survive       1
111          112  Did not survive       3
112          113  Did not survive       3
113          114  Did not survive       3
114          115  Did not survive       3
115          116  Did not survive       3
116          117  Did not survive       3
117          118  Did not survive       2
118          119  Did not survive       1
119          120  Did not survive       3
120          121  Did not survive       2
121          122  Did not survive       3
122          123  Did not survive       2
123          124         Survived       2
124          125  Did not survive       1
125          126         Survived       3
126          127  Did not survive       3
127          128         Survived       3
128          129         Survived       3
129          130  Did not survive       3
130          131  Did not survive       3
131          132  Did not survive       3
132          133  Did not survive       3
133          134         Survived       2
134          135  Did not survive       2
135          136  Did not survive       2
136          137         Survived       1
137          138  Did not survive       1
138          139  Did not survive       3
139          140  Did not survive       1
140          141  Did not survive       3
141          142         Survived       3
142          143         Survived       3
143          144  Did not survive       3
144          145  Did not survive       2
145          146  Did not survive       2
146          147         Survived       3
147          148  Did not survive       3
148          149  Did not survive       2
149          150  Did not survive       2
150          151  Did not survive       2
151          152         Survived       1
152          153  Did not survive       3
153          154  Did not survive       3
154          155  Did not survive       3
155          156  Did not survive       1
156          157         Survived       3
157          158  Did not survive       3
158          159  Did not survive       3
159          160  Did not survive       3
160          161  Did not survive       3
161          162         Survived       2
162          163  Did not survive       3
163          164  Did not survive       3
164          165  Did not survive       3
165          166         Survived       3
166          167         Survived       1
167          168  Did not survive       3
168          169  Did not survive       1
169          170  Did not survive       3
170          171  Did not survive       1
171          172  Did not survive       3
172          173         Survived       3
173          174  Did not survive       3
174          175  Did not survive       1
175          176  Did not survive       3
176          177  Did not survive       3
177          178  Did not survive       1
178          179  Did not survive       2
179          180  Did not survive       3
180          181  Did not survive       3
181          182  Did not survive       2
182          183  Did not survive       3
183          184         Survived       2
184          185         Survived       3
185          186  Did not survive       1
186          187         Survived       3
187          188         Survived       1
188          189  Did not survive       3
189          190  Did not survive       3
190          191         Survived       2
191          192  Did not survive       2
192          193         Survived       3
193          194         Survived       2
194          195         Survived       1
195          196         Survived       1
196          197  Did not survive       3
197          198  Did not survive       3
198          199         Survived       3
199          200  Did not survive       2
200          201  Did not survive       3
201          202  Did not survive       3
202          203  Did not survive       3
203          204  Did not survive       3
204          205         Survived       3
205          206  Did not survive       3
206          207  Did not survive       3
207          208         Survived       3
208          209         Survived       3
209          210         Survived       1
210          211  Did not survive       3
211          212         Survived       2
212          213  Did not survive       3
213          214  Did not survive       2
214          215  Did not survive       3
215          216         Survived       1
216          217         Survived       3
217          218  Did not survive       2
218          219         Survived       1
219          220  Did not survive       2
220          221         Survived       3
221          222  Did not survive       2
222          223  Did not survive       3
223          224  Did not survive       3
224          225         Survived       1
225          226  Did not survive       3
226          227         Survived       2
227          228  Did not survive       3
228          229  Did not survive       2
229          230  Did not survive       3
230          231         Survived       1
231          232  Did not survive       3
232          233  Did not survive       2
233          234         Survived       3
234          235  Did not survive       2
235          236  Did not survive       3
236          237  Did not survive       2
237          238         Survived       2
238          239  Did not survive       2
239          240  Did not survive       2
240          241  Did not survive       3
241          242         Survived       3
242          243  Did not survive       2
243          244  Did not survive       3
244          245  Did not survive       3
245          246  Did not survive       1
246          247  Did not survive       3
247          248         Survived       2
248          249         Survived       1
249          250  Did not survive       2
250          251  Did not survive       3
251          252  Did not survive       3
252          253  Did not survive       1
253          254  Did not survive       3
254          255  Did not survive       3
255          256         Survived       3
256          257         Survived       1
257          258         Survived       1
258          259         Survived       1
259          260         Survived       2
260          261  Did not survive       3
261          262         Survived       3
262          263  Did not survive       1
263          264  Did not survive       1
264          265  Did not survive       3
265          266  Did not survive       2
266          267  Did not survive       3
267          268         Survived       3
268          269         Survived       1
269          270         Survived       1
270          271  Did not survive       1
271          272         Survived       3
272          273         Survived       2
273          274  Did not survive       1
274          275         Survived       3
275          276         Survived       1
276          277  Did not survive       3
277          278  Did not survive       2
278          279  Did not survive       3
279          280         Survived       3
280          281  Did not survive       3
281          282  Did not survive       3
282          283  Did not survive       3
283          284         Survived       3
284          285  Did not survive       1
285          286  Did not survive       3
286          287         Survived       3
287          288  Did not survive       3
288          289         Survived       2
289          290         Survived       3
290          291         Survived       1
291          292         Survived       1
292          293  Did not survive       2
293          294  Did not survive       3
294          295  Did not survive       3
295          296  Did not survive       1
296          297  Did not survive       3
297          298  Did not survive       1
298          299         Survived       1
299          300         Survived       1
300          301         Survived       3
301          302         Survived       3
302          303  Did not survive       3
303          304         Survived       2
304          305  Did not survive       3
305          306         Survived       1
306          307         Survived       1
307          308         Survived       1
308          309  Did not survive       2
309          310         Survived       1
310          311         Survived       1
311          312         Survived       1
312          313  Did not survive       2
313          314  Did not survive       3
314          315  Did not survive       2
315          316         Survived       3
316          317         Survived       2
317          318  Did not survive       2
318          319         Survived       1
319          320         Survived       1
320          321  Did not survive       3
321          322  Did not survive       3
322          323         Survived       2
323          324         Survived       2
324          325  Did not survive       3
325          326         Survived       1
326          327  Did not survive       3
327          328         Survived       2
328          329         Survived       3
329          330         Survived       1
330          331         Survived       3
331          332  Did not survive       1
332          333  Did not survive       1
333          334  Did not survive       3
334          335         Survived       1
335          336  Did not survive       3
336          337  Did not survive       1
337          338         Survived       1
338          339         Survived       3
339          340  Did not survive       1
340          341         Survived       2
341          342         Survived       1
342          343  Did not survive       2
343          344  Did not survive       2
344          345  Did not survive       2
345          346         Survived       2
346          347         Survived       2
347          348         Survived       3
348          349         Survived       3
349          350  Did not survive       3
350          351  Did not survive       3
351          352  Did not survive       1
352          353  Did not survive       3
353          354  Did not survive       3
354          355  Did not survive       3
355          356  Did not survive       3
356          357         Survived       1
357          358  Did not survive       2
358          359         Survived       3
359          360         Survived       3
360          361  Did not survive       3
361          362  Did not survive       2
362          363  Did not survive       3
363          364  Did not survive       3
364          365  Did not survive       3
365          366  Did not survive       3
366          367         Survived       1
367          368         Survived       3
368          369         Survived       3
369          370         Survived       1
370          371         Survived       1
371          372  Did not survive       3
372          373  Did not survive       3
373          374  Did not survive       1
374          375  Did not survive       3
375          376         Survived       1
376          377         Survived       3
377          378  Did not survive       1
378          379  Did not survive       3
379          380  Did not survive       3
380          381         Survived       1
381          382         Survived       3
382          383  Did not survive       3
383          384         Survived       1
384          385  Did not survive       3
385          386  Did not survive       2
386          387  Did not survive       3
387          388         Survived       2
388          389  Did not survive       3
389          390         Survived       2
390          391         Survived       1
391          392         Survived       3
392          393  Did not survive       3
393          394         Survived       1
394          395         Survived       3
395          396  Did not survive       3
396          397  Did not survive       3
397          398  Did not survive       2
398          399  Did not survive       2
399          400         Survived       2
400          401         Survived       3
401          402  Did not survive       3
402          403  Did not survive       3
403          404  Did not survive       3
404          405  Did not survive       3
405          406  Did not survive       2
406          407  Did not survive       3
407          408         Survived       2
408          409  Did not survive       3
409          410  Did not survive       3
410          411  Did not survive       3
411          412  Did not survive       3
412          413         Survived       1
413          414  Did not survive       2
414          415         Survived       3
415          416  Did not survive       3
416          417         Survived       2
417          418         Survived       2
418          419  Did not survive       2
419          420  Did not survive       3
420          421  Did not survive       3
421          422  Did not survive       3
422          423  Did not survive       3
423          424  Did not survive       3
424          425  Did not survive       3
425          426  Did not survive       3
426          427         Survived       2
427          428         Survived       2
428          429  Did not survive       3
429          430         Survived       3
430          431         Survived       1
431          432         Survived       3
432          433         Survived       2
433          434  Did not survive       3
434          435  Did not survive       1
435          436         Survived       1
436          437  Did not survive       3
437          438         Survived       2
438          439  Did not survive       1
439          440  Did not survive       2
440          441         Survived       2
441          442  Did not survive       3
442          443  Did not survive       3
443          444         Survived       2
444          445         Survived       3
445          446         Survived       1
446          447         Survived       2
447          448         Survived       1
448          449         Survived       3
449          450         Survived       1
450          451  Did not survive       2
451          452  Did not survive       3
452          453  Did not survive       1
453          454         Survived       1
454          455  Did not survive       3
455          456         Survived       3
456          457  Did not survive       1
457          458         Survived       1
458          459         Survived       2
459          460  Did not survive       3
460          461         Survived       1
461          462  Did not survive       3
462          463  Did not survive       1
463          464  Did not survive       2
464          465  Did not survive       3
465          466  Did not survive       3
466          467  Did not survive       2
467          468  Did not survive       1
468          469  Did not survive       3
469          470         Survived       3
470          471  Did not survive       3
471          472  Did not survive       3
472          473         Survived       2
473          474         Survived       2
474          475  Did not survive       3

Vamos começar por verificar e eliminar duplicados

In [42]:
# Duplicados
print(df.duplicated())
df.drop_duplicates(inplace = True)

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280    False
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318    False
319    False
320    False
321    False
322    False
323    False
324    False
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
380    False
381    False
382    False
383    False
384    False
385    False
386    False
387    False
388    False
389    False
390    False
391    False
392    False
393    False
394    False
395    False
396    False
397    False
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437    False
438    False
439    False
440    False
441    False
442    False
443    False
444    False
445    False
446    False
447    False
448    False
449    False
450    False
451    False
452    False
453    False
454    False
455    False
456    False
457    False
458    False
459    False
460    False
461    False
462    False
463    False
464    False
465    False
466    False
467    False
468    False
469    False
470    False
471    False
472    False
473    False
474    False
475    False
476    False
477    False
478    False
479    False
480    False
481    False
482    False
483    False
484    False
485    False
486    False
487    False
488    False
489    False
490    False
491    False
492    False
493    False
494    False
495    False
496    False
497    False
498    False
499    False
500    False
501    False
502    False
503    False
504    False
505    False
506    False
507    False
508    False
509    False
510    False
511    False
512    False
513    False
514    False
515    False
516    False
517    False
518    False
519    False
520    False
521    False
522    False
523    False
524    False
525    False
526    False
527    False
528    False
529    False
530    False
531    False
532    False
533    False
534    False
535    False
536    False
537    False
538    False
539    False
540    False
541    False
542    False
543    False
544    False
545    False
546    False
547    False
548    False
549    False
550    False
551    False
552    False
553    False
554    False
555    False
556    False
557    False
558    False
559    False
560    False
561    False
562    False
563    False
564    False
565    False
566    False
567    False
568    False
569    False
570    False
571    False
572    False
573    False
574    False
575    False
576    False
577    False
578    False
579    False
580    False
581    False
582    False
583    False
584    False
585    False
586    False
587    False
588    False
589    False
590    False
591    False
592    False
593    False
594    False
595    False
596    False
597    False
598    False
599    False
600    False
601    False
602    False
603    False
604    False
605    False
606    False
607    False
608    False
609    False
610    False
611    False
612    False
613    False
614    False
615    False
616    False
617    False
618    False
619    False
620    False
621    False
622    False
623    False
624    False
625    False
626    False
627    False
628    False
629    False
630    False
631    False
632    False
633    False
634    False
635    False
636    False
637    False
638    False
639    False
640    False
641    False
642    False
643    False
644    False
645    False
646    False
647    False
648    False
649    False
650    False
651    False
652    False
653    False
654    False
655    False
656    False
657    False
658    False
659    False
660    False
661    False
662    False
663    False
664    False
665    False
666    False
667    False
668    False
669    False
670    False
671    False
672    False
673    False
674    False
675    False
676    False
677    False
678    False
679    False
680    False
681    False
682    False
683    False
684    False
685    False
686    False
687    False
688    False
689    False
690    False
691    False
692    False
693    False
694    False
695    False
696    False
697    False
698    False
699    False
700    False
701    False
702    False
703    False
704    False
705    False
706    False
707    False
708    False
709    False
710    False
711    False
712    False
713    False
714    False
715    False
716    False
717    False
718    False
719    False
720    False
721    False
722    False
723    False
724    False
725    False
726    False
727    False
728    False
729    False
730    False
731    False
732    False
733    False
734    False
735    False
736    False
737    False
738    False
739    False
740    False
741    False
742    False
743    False
744    False
745    False
746    False
747    False
748    False
749    False
750    False
751    False
752    False
753    False
754    False
755    False
756    False
757    False
758    False
759    False
760    False
761    False
762    False
763    False
764    False
765    False
766    False
767    False
768    False
769    False
770    False
771    False
772    False
773    False
774    False
775    False
776    False
777    False
778    False
779    False
780    False
781    False
782    False
783    False
784    False
785    False
786    False
787    False
788    False
789    False
790    False
791    False
792    False
793    False
794    False
795    False
796    False
797    False
798    False
799    False
800    False
801    False
802    False
803    False
804    False
805    False
806    False
807    False
808    False
809    False
810    False
811    False
812    False
813    False
814    False
815    False
816    False
817    False
818    False
819    False
820    False
821    False
822    False
823    False
824    False
825    False
826    False
827    False
828    False
829    False
830    False
831    False
832    False
833    False
834    False
835    False
836    False
837    False
838    False
839    False
840    False
841    False
842    False
843    False
844    False
845    False
846    False
847    False
848    False
849    False
850    False
851    False
852    False
853    False
854    False
855    False
856    False
857    False
858    False
859    False
860    False
861    False
862    False
863    False
864    False
865    False
866    False
867    False
868    False
869    False
870    False
871    False
872    False
873    False
874    False
875    False
876    False
877    False
878    False
879    False
880    False
881    False
882    False
883    False
884    False
885    False
886    False
887    False
888    False
889    False
890    False
dtype: bool

In [43]:
#Read datatypes origin 
print(df.dtypes)

PassengerId      int64
Survived        object
Pclass           int64
Name            object
Sex             object
Age              int32
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
LastName        object
FirstName       object
FamilySize       int64
Deck            object
Title           object
dtype: object

Ler datatypes e modificar para poder ter definido os tipos por colunas.

In [45]:
#import pandas as pd
# Mudar os datatypes
# Ler dataset e mostrar datatypes atuais
#df = pd.read_csv('Titanic-Dataset - copia.csv')
print("Original Data Types:")
print(df.dtypes)

# Redefinição de datatypes
df = df.astype({
    'Pclass': 'int8',      
    'Age': 'int8',      
    'SibSp': 'int8',    
    'Parch': 'int8',       
    'Fare': 'float32',     
    'Sex': 'category',     
    'Embarked': 'category' 
})

# Verificar
print("\nRedefined Data Types:")
print(df.dtypes)

# Guardar na memória
print("\nMemory Usage (Reduced):")
print(df.memory_usage(deep=True))

Original Data Types:
PassengerId      int64
Survived        object
Pclass           int64
Name            object
Sex             object
Age              int32
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
LastName        object
FirstName       object
FamilySize       int64
Deck            object
Title           object
dtype: object

Redefined Data Types:
PassengerId       int64
Survived         object
Pclass             int8
Name             object
Sex            category
Age                int8
SibSp              int8
Parch              int8
Ticket           object
Fare            float32
Cabin            object
Embarked       category
LastName         object
FirstName        object
FamilySize        int64
Deck             object
Title            object
dtype: object

Memory Usage (Reduced):
Index            132
PassengerId     7128
Survived       54630
Pclass           891
Name           67685
Sex             1107
Age              891
SibSp            891
Parch            891
Ticket         49674
Fare            3564
Cabin          44550
Embarked        1149
LastName       49758
FirstName      59802
FamilySize      7128
Deck           44550
Title          45769
dtype: int64

In [46]:
#Imprimir toda a informação da tabela 
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    object
 2   Pclass       891 non-null    int8
 3   Name         891 non-null    object
 4   Sex          891 non-null    category
 5   Age          891 non-null    int8
 6   SibSp        891 non-null    int8
 7   Parch        891 non-null    int8
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float32
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    category
 12  LastName     891 non-null    object
 13  FirstName    891 non-null    object
 14  FamilySize   891 non-null    int64
 15  Deck         891 non-null    object
 16  Title        874 non-null    object
dtypes: category(2), float32(1), int64(2), int8(4), object(8)
memory usage: 78.7+ KB
None

Formatar Strings para elas ficarem uniformes.

In [48]:
#format strings

df['Name'] = df['Name'].str.title() 
df['Sex'] = df['Sex'].str.lower()
df['Cabin'] = df['Cabin'].str.title()
df['Ticket'] = df['Ticket'].str.title() 
print(df)

     PassengerId         Survived  Pclass  \
0              1  Did not survive       3
1              2         Survived       1
2              3         Survived       3
3              4         Survived       1
4              5  Did not survive       3
5              6  Did not survive       3
6              7  Did not survive       1
7              8  Did not survive       3
8              9         Survived       3
9             10         Survived       2
10            11         Survived       3
11            12         Survived       1
12            13  Did not survive       3
13            14  Did not survive       3
14            15  Did not survive       3
15            16         Survived       2
16            17  Did not survive       3
17            18         Survived       2
18            19  Did not survive       3
19            20         Survived       3
20            21  Did not survive       2
21            22         Survived       2
22            23         Survived       3
23            24         Survived       1
24            25  Did not survive       3
25            26         Survived       3
26            27  Did not survive       3
27            28  Did not survive       1
28            29         Survived       3
29            30  Did not survive       3
30            31  Did not survive       1
31            32         Survived       1
32            33         Survived       3
33            34  Did not survive       2
34            35  Did not survive       1
35            36  Did not survive       1
36            37         Survived       3
37            38  Did not survive       3
38            39  Did not survive       3
39            40         Survived       3
40            41  Did not survive       3
41            42  Did not survive       2
42            43  Did not survive       3
43            44         Survived       2
44            45         Survived       3
45            46  Did not survive       3
46            47  Did not survive       3
47            48         Survived       3
48            49  Did not survive       3
49            50  Did not survive       3
50            51  Did not survive       3
51            52  Did not survive       3
52            53         Survived       1
53            54         Survived       2
54            55  Did not survive       1
55            56         Survived       1
56            57         Survived       2
57            58  Did not survive       3
58            59         Survived       2
59            60  Did not survive       3
60            61  Did not survive       3
61            62         Survived       1
62            63  Did not survive       1
63            64  Did not survive       3
64            65  Did not survive       1
65            66         Survived       3
66            67         Survived       2
67            68  Did not survive       3
68            69         Survived       3
69            70  Did not survive       3
70            71  Did not survive       2
71            72  Did not survive       3
72            73  Did not survive       2
73            74  Did not survive       3
74            75         Survived       3
75            76  Did not survive       3
76            77  Did not survive       3
77            78  Did not survive       3
78            79         Survived       2
79            80         Survived       3
80            81  Did not survive       3
81            82         Survived       3
82            83         Survived       3
83            84  Did not survive       1
84            85         Survived       2
85            86         Survived       3
86            87  Did not survive       3
87            88  Did not survive       3
88            89         Survived       1
89            90  Did not survive       3
90            91  Did not survive       3
91            92  Did not survive       3
92            93  Did not survive       1
93            94  Did not survive       3
94            95  Did not survive       3
95            96  Did not survive       3
96            97  Did not survive       1
97            98         Survived       1
98            99         Survived       2
99           100  Did not survive       2
100          101  Did not survive       3
101          102  Did not survive       3
102          103  Did not survive       1
103          104  Did not survive       3
104          105  Did not survive       3
105          106  Did not survive       3
106          107         Survived       3
107          108         Survived       3
108          109  Did not survive       3
109          110         Survived       3
110          111  Did not survive       1
111          112  Did not survive       3
112          113  Did not survive       3
113          114  Did not survive       3
114          115  Did not survive       3
115          116  Did not survive       3
116          117  Did not survive       3
117          118  Did not survive       2
118          119  Did not survive       1
119          120  Did not survive       3
120          121  Did not survive       2
121          122  Did not survive       3
122          123  Did not survive       2
123          124         Survived       2
124          125  Did not survive       1
125          126         Survived       3
126          127  Did not survive       3
127          128         Survived       3
128          129         Survived       3
129          130  Did not survive       3
130          131  Did not survive       3
131          132  Did not survive       3
132          133  Did not survive       3
133          134         Survived       2
134          135  Did not survive       2
135          136  Did not survive       2
136          137         Survived       1
137          138  Did not survive       1
138          139  Did not survive       3
139          140  Did not survive       1
140          141  Did not survive       3
141          142         Survived       3
142          143         Survived       3
143          144  Did not survive       3
144          145  Did not survive       2
145          146  Did not survive       2
146          147         Survived       3
147          148  Did not survive       3
148          149  Did not survive       2
149          150  Did not survive       2
150          151  Did not survive       2
151          152         Survived       1
152          153  Did not survive       3
153          154  Did not survive       3
154          155  Did not survive       3
155          156  Did not survive       1
156          157         Survived       3
157          158  Did not survive       3
158          159  Did not survive       3
159          160  Did not survive       3
160          161  Did not survive       3
161          162         Survived       2
162          163  Did not survive       3
163          164  Did not survive       3
164          165  Did not survive       3
165          166         Survived       3
166          167         Survived       1
167          168  Did not survive       3
168          169  Did not survive       1
169          170  Did not survive       3
170          171  Did not survive       1
171          172  Did not survive       3
172          173         Survived       3
173          174  Did not survive       3
174          175  Did not survive       1
175          176  Did not survive       3
176          177  Did not survive       3
177          178  Did not survive       1
178          179  Did not survive       2
179          180  Did not survive       3
180          181  Did not survive       3
181          182  Did not survive       2
182          183  Did not survive       3
183          184         Survived       2
184          185         Survived       3
185          186  Did not survive       1
186          187         Survived       3
187          188         Survived       1
188          189  Did not survive       3
189          190  Did not survive       3
190          191         Survived       2
191          192  Did not survive       2
192          193         Survived       3
193          194         Survived       2
194          195         Survived       1
195          196         Survived       1
196          197  Did not survive       3
197          198  Did not survive       3
198          199         Survived       3
199          200  Did not survive       2
200          201  Did not survive       3
201          202  Did not survive       3
202          203  Did not survive       3
203          204  Did not survive       3
204          205         Survived       3
205          206  Did not survive       3
206          207  Did not survive       3
207          208         Survived       3
208          209         Survived       3
209          210         Survived       1
210          211  Did not survive       3
211          212         Survived       2
212          213  Did not survive       3
213          214  Did not survive       2
214          215  Did not survive       3
215          216         Survived       1
216          217         Survived       3
217          218  Did not survive       2
218          219         Survived       1
219          220  Did not survive       2
220          221         Survived       3
221          222  Did not survive       2
222          223  Did not survive       3
223          224  Did not survive       3
224          225         Survived       1
225          226  Did not survive       3
226          227         Survived       2
227          228  Did not survive       3
228          229  Did not survive       2
229          230  Did not survive       3
230          231         Survived       1
231          232  Did not survive       3
232          233  Did not survive       2
233          234         Survived       3
234          235  Did not survive       2
235          236  Did not survive       3
236          237  Did not survive       2
237          238         Survived       2
238          239  Did not survive       2
239          240  Did not survive       2
240          241  Did not survive       3
241          242         Survived       3
242          243  Did not survive       2
243          244  Did not survive       3
244          245  Did not survive       3
245          246  Did not survive       1
246          247  Did not survive       3
247          248         Survived       2
248          249         Survived       1
249          250  Did not survive       2
250          251  Did not survive       3
251          252  Did not survive       3
252          253  Did not survive       1
253          254  Did not survive       3
254          255  Did not survive       3
255          256         Survived       3
256          257         Survived       1
257          258         Survived       1
258          259         Survived       1
259          260         Survived       2
260          261  Did not survive       3
261          262         Survived       3
262          263  Did not survive       1
263          264  Did not survive       1
264          265  Did not survive       3
265          266  Did not survive       2
266          267  Did not survive       3
267          268         Survived       3
268          269         Survived       1
269          270         Survived       1
270          271  Did not survive       1
271          272         Survived       3
272          273         Survived       2
273          274  Did not survive       1
274          275         Survived       3
275          276         Survived       1
276          277  Did not survive       3
277          278  Did not survive       2
278          279  Did not survive       3
279          280         Survived       3
280          281  Did not survive       3
281          282  Did not survive       3
282          283  Did not survive       3
283          284         Survived       3
284          285  Did not survive       1
285          286  Did not survive       3
286          287         Survived       3
287          288  Did not survive       3
288          289         Survived       2
289          290         Survived       3
290          291         Survived       1
291          292         Survived       1
292          293  Did not survive       2
293          294  Did not survive       3
294          295  Did not survive       3
295          296  Did not survive       1
296          297  Did not survive       3
297          298  Did not survive       1
298          299         Survived       1
299          300         Survived       1
300          301         Survived       3
301          302         Survived       3
302          303  Did not survive       3
303          304         Survived       2
304          305  Did not survive       3
305          306         Survived       1
306          307         Survived       1
307          308         Survived       1
308          309  Did not survive       2
309          310         Survived       1
310          311         Survived       1
311          312         Survived       1
312          313  Did not survive       2
313          314  Did not survive       3
314          315  Did not survive       2
315          316         Survived       3
316          317         Survived       2
317          318  Did not survive       2
318          319         Survived       1
319          320         Survived       1
320          321  Did not survive       3
321          322  Did not survive       3
322          323         Survived       2
323          324         Survived       2
324          325  Did not survive       3
325          326         Survived       1
326          327  Did not survive       3
327          328         Survived       2
328          329         Survived       3
329          330         Survived       1
330          331         Survived       3
331          332  Did not survive       1
332          333  Did not survive       1
333          334  Did not survive       3
334          335         Survived       1
335          336  Did not survive       3
336          337  Did not survive       1
337          338         Survived       1
338          339         Survived       3
339          340  Did not survive       1
340          341         Survived       2
341          342         Survived       1
342          343  Did not survive       2
343          344  Did not survive       2
344          345  Did not survive       2
345          346         Survived       2
346          347         Survived       2
347          348         Survived       3
348          349         Survived       3
349          350  Did not survive       3
350          351  Did not survive       3
351          352  Did not survive       1
352          353  Did not survive       3
353          354  Did not survive       3
354          355  Did not survive       3
355          356  Did not survive       3
356          357         Survived       1
357          358  Did not survive       2
358          359         Survived       3
359          360         Survived       3
360          361  Did not survive       3
361          362  Did not survive       2
362          363  Did not survive       3
363          364  Did not survive       3
364          365  Did not survive       3
365          366  Did not survive       3
366          367         Survived       1
367          368         Survived       3
368          369         Survived       3
369          370         Survived       1
370          371         Survived       1
371          372  Did not survive       3
372          373  Did not survive       3
373          374  Did not survive       1
374          375  Did not survive       3
375          376         Survived       1
376          377         Survived       3
377          378  Did not survive       1
378          379  Did not survive       3
379          380  Did not survive       3
380          381         Survived       1
381          382         Survived       3
382          383  Did not survive       3
383          384         Survived       1
384          385  Did not survive       3
385          386  Did not survive       2
386          387  Did not survive       3
387          388         Survived       2
388          389  Did not survive       3
389          390         Survived       2
390          391         Survived       1
391          392         Survived       3
392          393  Did not survive       3
393          394         Survived       1
394          395         Survived       3
395          396  Did not survive       3
396          397  Did not survive       3
397          398  Did not survive       2
398          399  Did not survive       2
399          400         Survived       2
400          401         Survived       3
401          402  Did not survive       3
402          403  Did not survive       3
403          404  Did not survive       3
404          405  Did not survive       3
405          406  Did not survive       2
406          407  Did not survive       3
407          408         Survived       2
408          409  Did not survive       3
409          410  Did not survive       3
410          411  Did not survive       3
411          412  Did not survive       3
412          413         Survived       1
413          414  Did not survive       2
414          415         Survived       3
415          416  Did not survive       3
416          417         Survived       2
417          418         Survived       2
418          419  Did not survive       2
419          420  Did not survive       3
420          421  Did not survive       3
421          422  Did not survive       3
422          423  Did not survive       3
423          424  Did not survive       3
424          425  Did not survive       3
425          426  Did not survive       3
426          427         Survived       2
427          428         Survived       2
428          429  Did not survive       3
429          430         Survived       3
430          431         Survived       1
431          432         Survived       3
432          433         Survived       2
433          434  Did not survive       3
434          435  Did not survive       1
435          436         Survived       1
436          437  Did not survive       3
437          438         Survived       2
438          439  Did not survive       1
439          440  Did not survive       2
440          441         Survived       2
441          442  Did not survive       3
442          443  Did not survive       3
443          444         Survived       2
444          445         Survived       3
445          446         Survived       1
446          447         Survived       2
447          448         Survived       1
448          449         Survived       3
449          450         Survived       1
450          451  Did not survive       2
451          452  Did not survive       3
452          453  Did not survive       1
453          454         Survived       1
454          455  Did not survive       3
455          456         Survived       3
456          457  Did not survive       1
457          458         Survived       1
458          459         Survived       2
459          460  Did not survive       3
460          461         Survived       1
461          462  Did not survive       3
462          463  Did not survive       1
463          464  Did not survive       2
464          465  Did not survive       3
465          466  Did not survive       3
466          467  Did not survive       2
467          468  Did not survive       1
468          469  Did not survive       3
469          470         Survived       3
470          471  Did not survive       3
471          472  Did not survive       3
472          473         Survived       2
473          474         Survived       2
474          475  Did not survive       3

Vamos verificar as primeiras linhas para ver se ficou com a formatação pretendida

In [50]:
#Imprimir algumas linhas 
#import pandas as pd
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,LastName,FirstName,FamilySize,Deck,Title
0,1,Did not survive,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.250000,A,S,Braund,Mr. Owen Harris,2,A,Mr
1,2,Survived,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,Pc 17599,71.283302,C,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer),2,C,Mrs
2,3,Survived,3,"Heikkinen, Miss. Laina",female,26,0,0,Ston/O2. 3101282,7.925000,U,S,Heikkinen,Miss. Laina,1,U,Miss
3,4,Survived,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.099998,C,S,Futrelle,Mrs. Jacques Heath (Lily May Peel),2,C,Mrs
4,5,Did not survive,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.050000,U,S,Allen,Mr. William Henry,1,U,Mr

Outro dado que considero importante para a investigação é saber qual era o número total de passageiros do Titanic

In [52]:
#import pandas as pd
#Número de passageiros 
#  Ler o csv dataset
# df = pd.read_csv('Titanic-Dataset - copia.csv')

# Calcular o total de passageiros do navio
total_passengers = len(df)
print(f"Total number of passengers on board: {total_passengers}")

Total number of passengers on board: 891

Também pretendo saber quantos tripulantes iriam abordo do mesmo navio

In [54]:
#Número de tripulantes
total_crew =total - total_passengers
print(total_crew)

1333

O dado mais curioso foi calcular a taxa de sobrevivência tebdo por base todos os dados do dataset e o número de pessoas abordo dado pelo documento texto e saber que era muito baixa a probabilidade de sobreviência.

In [56]:
# Calcular taxa de sobrevivencia 
#df = pd.read_csv('Titanic-Dataset-Copy1.csv')


count_survive = df['Survived'].str.count('Survive').sum()


total_rows = len(df)

percentage_survive = (count_survive / total_rows) * 100


print(f"Count of 'Survive': {count_survive}")
print(f"Percentage of 'Survive': {percentage_survive:.2f}%")


count_survive = df['Survived'].str.count('Survive').sum()

Count of 'Survive': 342
Percentage of 'Survive': 38.38%

Para terminar é feita uma última verificação aos valores e a existência de valores nulos e da sua ocupação em memória. 
Verificamos que só a coluna dos títulos familiaresn contém valores nulos. 
É feita a gravação de um novo ficheiro csv com o nome definido.

In [58]:
#Verificar se existem valores nulos e gravar novo CSV
print("\nMissing values after handling:")
print(df.isna().sum())


output_csv_path = "cleaned_datah0k.csv"  
df.to_csv(output_csv_path, index=False)

#Confirmar a gravação
print(f"Cleaned data saved to {output_csv_path}")
print("I turn MSUD 2 to code")
print("stop run")

Missing values after handling:
PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age             0
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin           0
Embarked        0
LastName        0
FirstName       0
FamilySize      0
Deck            0
Title          17
dtype: int64
Cleaned data saved to cleaned_datah0k.csv
I turn MSUD 2 to code
stop run

<------------------------------------------------------------------------------------------------------------------------>
É apresentada a confirmação de gravação do mesmo e de duas mensagens com algum humor no final.
Considerações foi divertido este jogo de lógica e procura de padrões. 
<------------------------------------------------------------------------------------------------------------------------>